---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "trabajo ciencia abierta"
author: "Javiera Abreu"
date: "26/5/2020"
output: pdf_document
---

Universidad de Chile
Facultad de Ciencias Sociales
Carrera de Sociología
Estrategias de Investigación Cuantitativa
Profesor: Maria Constanza Ayala
Ayudante: Camila Ortiz










###*Y ahora, ¿con quién dejamos a las niñas, niñes y niños?* 

####Trabajo de investigación sobre las estrategias de cuidado infantil según género y clase social en colegios "Escuela Carlos Pezoa Veliz", "Peter College" y "Saint George"







*Integrantes:* Josefina Carrasco, Javiera Carvajal, Alejandra Deleaveau, Valentina González, Catalina Flores, Valentina Martínez

Santiago, 12 de enero, 2019.

*1. Pregunta y objetivos de investigación* 

Pregunta de investigación:

¿Cuáles son las diferencias en las estrategias de cuidado respecto a los niños/as que eligen las mujeres apoderadas de los colegios "Escuela Carlos Pezoa Véliz", "Peter College" y "Saint George College"?

Objetivo General:

Comparar las diferencias en las estrategias de cuidado a los niños/as que eligen las mujeres de acuerdo a la clase social, en los colegios "Escuela Carlos Pezoa Véliz", "Peter College" y "Saint George´s College".

Objetivos específicos

1- Identificar el género de la persona que se hace cargo del cuidado y de quién decide sobre la estrategias de cuidado, según clase social, a partir de la caracterización socio-económica de los colegios Saint George, Peter College y Escuela Carlos Pezoa Veliz.
2.- Identificar la relación con el niño de la persona que se hace cargo del cuidado, al igual que identificar si estas perciben las labores de cuidado como un trabajo
3.- Identificar la relación entre clase social y trabajo de cuidado remunerado, además de identificar qué tipo de tareas relacionadas al cuidado son remuneradas.
4- Identificar la relación entre característica socioeconómicas de los colegios y tipos de estrategias de cuidado, entendidas en base al género y la remuneración.


*2. Hipótesis*

La hipótesis correspondiente al objetivo general es la siguiente: Las estrategias de cuidado variarán según   la característica socio-económica de los colegios; es decir, en el colegio caracterizado como nivel socioeconómico bajo las mujeres optarán a estrategias de cuidado no remunerado, mientras que en el colegio de nivel alto las estrategias de cuidado infantil que predominarán son las remuneradas. Sin embargo, se cree que la persona que, principalmente, está encargada del cuidado transversalmente será una mujer, mientras que los hombres sólo harán tareas asistenciales.

1.-Respecto del primer objetivo específico, se espera que la persona que se hace cargo del cuidado al igual que la persona que decide las estrategias de cuidado sea del género femenino, independientemente de la caracterización socioeconómica del colegio. Esto debido a que el rol de género que asume la mujer (Vaquiro y Stiepovic, 2010) está basado en relaciones de afecto y actividades domésticas dentro de la estructura familiar. En esta misma línea, la familia y las funciones atribuidas a esta (social, educativa, laboral y de poder) han sido fundamentales para entender a la mujer como la persona que asume el rol de cuidado, en su calidad de madre, esposa, abuela o hija. Presentándose la mujer, entonces, como la cuidadora principal, el rol del hombre pasa a ser tan solo asistencial en la mayoría de los escenarios, teniendo variaciones de acuerdo con la clase social a la que pertenece. Además, la figura del/la cuidador/a principal en tanto eje central en el sistema familiar en la medida en que se hace cargo del cuidado se involucra, finalmente, con otras personas y, a su vez, asumen el deterioro de lo que significa hacerse cargo de esta tarea.

2.- En relación al objetivo 2, se espera que las personas que, primordialmente, se hacen cargo de los cuidados del niño sean sus madres y/o abuelas, al igual que se espera que éstas no consideren como trabajo las tareas provenientes del cuidado del niño, más bien como parte de su "rol de madre". Según Moreno-Roldán, Agudelo-Bedoya & Alzate-Pulgarín (2018), se reconoce la presencia de redes (de tipo familiar, institucional o vecinal) que existen para el cuidado tanto para cuidadoras o cuidadores principales como para el apoyo en "figuras subsidiarias", siendo fundamental el apoyo que brinda la abuela, y que se gesta a partir de la sensación de "obligación" que tienen respecto a la situación del cuidado. 
 
3.-En torno al tercer objetivo específico, se espera que sea mayor la remuneración del cuidado en el colegio socioeconómico alta, mientras que en los colegios de clase media y media baja estas cifras sean bajas o nulas. A su vez, se espera que algunas tareas relacionadas con el cuidado sean remuneradas, tales como llevar a los niños a la escuela, mientras que otras tareas como bañarlos o hacerlos dormir no lo sean. Según Flaquer, Pfau-Effinger & Leiras (2014) hay tres tipos de cuidado: *cuidado formal, que hace referencia a "formas de cuidado reguladas en función de las condiciones fijadas por un marco jurídico"; **informal, que  corresponde a la actividad que no está regulada, no se encuentran dentro del marco jurídico establecido por el estado, el mercado, la sociedad o la familia, estos pueden ser con o sin remuneración; **semiformal*, que refiere a formas reguladas del cuidado pero que no corresponden a un empleo remunerado formal, por ejemplo, cuando existe apoyo económico estatal frente al cuidado.

4.-Finalmente, en relación con el último objetivo, se espera que los establecimientos presenten distintas estrategias de cuidado entendidas en base al género y la remuneración, con una carga en relación con el rol de madre. Se espera que, en todos los establecimientos, exista coincidencia en la dimensión de género de la estrategia, optando la mayoría de las apoderadas por mujeres -considerándose a ellas mismas- para encargarse principalmente del cuidado, aunque variando en la clase alta, en la cual se reconocerá una proporción baja de hombres a cargo del cuidado. Por otra parte, mientras que las mujeres de clase alta optarán, en parte, por "Mujer con remuneración", las de clase media lo harán en menor proporción y las de clase media-baja, principalmente, optarán por la estrategia "Mujer sin remuneración". Estas diferencias serán significativas estadísticamente, es decir, tanto a nivel muestral como poblacional podrán reconocerse (bajo el falso supuesto de muestreo probabilístico) a partir de la revisión bibliográfica, la cual indica que las estrategias de cuidado, es decir, la delimitación de quién y cómo se harán cargo del cuidado de la/el menor, están condicionadas económicamente; existen distinciones de clase para las estrategias de cuidado, entendiendo las clases según la operacionalización de Cano (2018), quien indica que son los profesionales quienes cuentan con más recursos provenientes de su mejor ubicación dentro del mercado laboral, ya que pueden optar a redes institucionales como colegios y sala cunas, además de redes informales. Además, cuentan con ventajas a nivel del trabajo, puesto que tienen beneficios, como lo es el fuero maternal, y que va disminuyendo a medida que se desciende en la escala social, evidenciándose un mayor malestar, pues gran parte, en el caso de las mujeres, debe cumplir una doble jornada laboral al mismo  al mismo tiempo en que lidian con patrones desiguales del reparto del trabajo dentro del hogar.




*3. Diseño Metodológico*

De acuerdo con la pregunta de investigación y los objetivos correspondientes planteados anteriormente, las variables a utilizar serán las estrategias de cuidado, la clase social y el género. Teniendo en cuenta los objetivos del estudio, se puede clasificar la investigación como correlacional, pues la mayoría de los objetivos esbozados apuntan a relacionar las características de las estrategias de cuidado en relación al género y a la clase social, develando la manera en que se manifiestan estos hechos por medio de las presentes variables dependientes e independiente, respectivamente. 
Para responder nuestras hipótesis y objetivos de investigación se recogió información durante los meses de noviembre y diciembre del 2018 mediante la aplicación de encuestas a una muestra de 45 mujeres apoderadas de tres colegios de distintas comunas de Santiago, donde en cada colegio se aplicaron las encuestas a 15 mujeres con el objetivo de tener la misma cantidad de madres y así poder comparar los resultados finales entre los colegios. Los colegios son la "Escuela Carlos Pezoa Véliz", "Peter College" y "Saint George College" de las comunas de Quinta Normal, Cerrillos y Vitacura, respectivamente. Se seleccionó a estos colegios puesto que están clasificados como medio-bajo, medio-alto y alto, respectivamente, según la Agencia de Calidad de la Educación perteneciente al MINEDUC, en base a criterios de vulnerabilidad de las/os niñas/os e ingreso y nivel educacional alcanzado de las/os apoderadas/os. La selección de la muestra y la posterior recolección de datos no fueron realizadas a través de un muestreo aleatorio o probabilístico, sino que más bien  fueron elegidos según los criterios teóricos. En primer lugar, basándose en la representatividad de grupos, entendiendo por esto a la clase social, la cual se vincula con las personas y familias que conforman lo que es el contorno de la comunidad educacional. En segundo lugar, en base al criterio de accesibilidad para el grupo de investigación, considerando redes y recursos de este mismo. No obstante, cabe destacar que hubo algunos obstáculos durante el proceso de selección de la muestra, puesto que había un tiempo limitado para aplicar las encuestas, especialmente a causa de la finalización del período académico de los colegios, y también debido a las dificultades administrativas que presentaban algunos colegios. 
A las apoderadas de la "Escuela Carlos Pezoa Véliz" se les entregó la encuesta presencialmente, mientras que a las madres apoderadas de los colegios "Peter College" y "Saint George College" se les envió la encuesta mediante formulario de cuestionarios Google. Se desprende, por tanto, que se trata de un estudio con metodología observacional, pues se medirán las variables de interés intentando no influir en las respuestas de las personas a quienes se dirige el estudio, teniendo un nivel de control que no va más allá de las variables que puede abarcar cada respuesta
Por último, se presenta como necesidad ocupar técnicas inferenciales que midan variables categóricas es decir, variables nominales y ordinales, por lo que se llevará a cabo el análisis de estas por medio de Chi2, el cual permitirá observar la relación entre estas variables, reconocer si las diferencias son estadísticamente significativas y el tamaño del efecto a partir del estadístico V de Cramer.  
Respecto a las limitaciones del diseño metodológico de la investigación, en primer lugar, respecto al uso de estadísticos inferenciales, al no utilizar un muestreo probabilístico para la seleccionar la muestra, se imposibilita la extrapolación de los resultados al total de la población. Esto son válidos únicamente para la muestra,, en este caso, para los apoderados de los colegios "Escuela Carlos Pezoa Véliz", "Colegio Excelsior" y "Saint George College". Aún así, se realizarán las inferencias poblacionales sin que estas, necesariamente, representen a la población con un nivel de confianza determinado. 
Otra limitación que se mantuvo durante el diseño metodológico de la investigación es que en su mayoría las variables son nominales, por lo que no se podrá analizar las medidas de tendencia central para éstas; más bien, sólo se podrá hacer mediante una tabla de frecuencias; a su vez, como la variable ingreso está dividida en tramos tampoco se podrá sacar un promedio exacto de cuánto ingresos recibe la población de la muestra.

*4. Resultados*

Para los presentes resultados, dado que el muestreo no fue aleatorio probabilístico, las inferencias poblacionales que se realizan en el análisis no tienen certeza con el nivel de confianza aplicado, sino que solamente poseen un valor analítico y representan a la muestra seleccionada. Aun así, estos resultados pueden ser corroborados con información desde muestras aleatorias en la posteridad.
 
*a. Género*

En primer lugar, se presenta la tabla 1 para identificar la relación entre género y cuidado según las tendencias en las estrategias de cuidado de cada familia, en general.

AQUI VA LA TABLA 1 "FRECUENCIA RELATIVA PORCENTUAL DE LA DISTRIBUCIÓN DE TAREAS DE CUIDADO SEGUN GÉNERO"

 
Según los datos observados, las mujeres son quienes se hacen cargo mayoritariamente tanto del cuidado de los/as niños/as como de la planificación de este. El primer punto se expresa en que quienes se hacen cargo del cuidado principalmente (cuidador o cuidadora principal) son mujeres en un 100%. Los niveles más altos de participación masculina en tareas de cuidado se concentran en llevar y recoger de la escuela (17,78% y 13,33% respectivamente), junto con hacer dormir a el/la niño/a (13,33%). Las mujeres, por su parte, son las que se hacen cargo mayoritariamente, en toda la muestra, de todas las tareas, encontrando el nivel más bajo de participación en las tareas de llevar a la escuela y hacer dormir (82,22% ambas), siendo este, de todas formas, considerablemente mayor al de participación masculina en las tareas. Debido a estos resultados es que se puede afirmar que independiente a la clase social las mujeres son quienes se hacen cargo del cuidado. No se puede hacer prueba de hipótesis de chi-cuadrado para ver la relación entre las variables debido a que el 100% de las personas que se hacen cargo del cuidado son mujeres, por lo que no se cumplen los requisitos para la prueba.

*b. Rol de madre*

AQUI VA LA TABLA 7 FRECUENCIA RELATIVA PORCENTUAL DE RELACIÓN DE CUIDADORA/OR CON EL MENOR
 
En relación al objetivo dos, en todas las tareas sobre el cuidado las madres y/o abuelas son las que se hacen cargo, esto se puede ver en la tabla 7 donde la categoría madre contiene las relaciones de madre y abuela. Las tareas con mayor porcentaje son las de contención emocional (91,11%), apoyo con las tareas escolares (91,11%) y levantar en las mañanas (95,56%), por lo que se puede agregar a la información anterior que, además de ser mujeres las que se hacen cargo, estas son mayoritariamente madres o abuelas del infante.

AQUI VA LA TABLA 6 FRECUENCIA RELATIVA PORCENTUAL DE CONSIEDERACION DEL CUIDADO COMO TRABAJO

Respecto a la tabla anterior, se puede identificar si las labores de cuidado son entendidas como trabajo por parte de las mujeres encuestadas. Como respuesta a la pregunta: "¿Considera que estas labores son un trabajo?", el 46,67% de las mujeres contestó que sí, un 40% contestó que no, un 4,44% que no sabía y un 8,89% no respondió. Con estos resultados a nivel muestral, se puede explicar que la poca diferencia entre creer que el trabajo de cuidado es un trabajo y no hacerlo, considerando la bibliografía revisada y que son sólo mujeres las que se encargan del cuidado en general, reside en la naturalización que hay de la mujer como madre, como la encargada natural del trabajo de cuidado. Por ende, la realización de estas tareas serían parte del rol de madre y no como un trabajo reconocido. 

*c. Remuneración*

Se presenta la tabla 2 para identificar la presencia o ausencia de remuneración del cuidado según las tendencias en las estrategias de cuidado de cada familia de la muestra
 
AQUI VA LA TABLA 2 FRECUENCIA RELATIVA PORCENTUAL DE REMUNERACION A LA PERSONA QUE SE HAE CARGO DE LAS TAREAS DE CUIDADO
 
Se puede observar que hay un porcentaje mayor de personas que realizan trabajos de cuidado de manera no remunerada, donde un 80% no recibe remuneración y 20% sí. Existen sólo algunas de las tareas que son realizadas con remuneración dentro de la muestra, tales como  "preparar la comida" (26,67); "llevar a la escuela" (11,11%); "recoger a la escuela" (22,22%); "ausencia de encargado principal" (20%). Tareas como la contención emocional, apoyo con tareas escolares, hacer dormir, corrección del comportamiento y levantar en la mañana no son remuneradas en ninguno de los casos (sobre la estrategia mayormente utilizada), implicando que el cuidado, en general, es un trabajo no remunerado, el cual sólo en determinadas tareas y en la minoría de los casos es realizado de forma remunerada. 

Para observar la relación entre remuneración del trabajo del cuidado y la clase social, se presenta la tabla de contingencia entre ambas variables y se  realiza la prueba de hipótesis de chi-cuadrado. 

AQUI VA LA TABLA 4 FRECUENCIA ABSOLUTA DE REMUNERACION PARA ENCARGADE PRINCIPAL DEL CUIDADO SEUN NIVEL SOICOECONOMICO

En la Tabla 4 se identifica la relación entre "Remuneración" y  "Clase social", para la persona encargada del cuidado, en la cual se muestra que las personas que realizan trabajos de cuidado en la clase baja totalidad no recibe remuneración por su labor µµen su totalidad. En el establecimiento de clase media solo una recibe remuneración. Esto cambia en la clase alta donde 8 personas reciben remuneración mientras 7 no lo hacen. A nivel general de 45 casos, 36 realizan tareas de cuidado sin remuneración. Por lo que se puede observar que, a nivel muestral, las personas que realizan los trabajos de cuidado lo hacen de manera gratuita, aunque a nivel socioeconómico alto la mayoría de las encargadas del cuidado reciben remuneración por ello.

AQUI VA LA TABÑA 5 PRUEBA CHICUADRADO Y TAMAÑO DEL EFECTO CON V DE CRAMER PARA REMUNERACION

A partir de la prueba de hipótesis Chi-cuadrado, bajo el supuesto falso de una muestra probabilísticamente construida con un nivel de confianza del 95%, se reconoce que la relación entre los grupos es estadísticamente significativa, es decir, que no hay independencia entre las variables "Remuneración" y "Clase social", por lo tanto, se rechaza la hipótesis nula de independencia de variables. Esto quiere decir que las diferencias que se reconocen en la tabla de contingencia pueden darse, con un 95% de confianza, en la población. Según el test V de Cramer, el tamaño del efecto de esta relación es de 0,593, es decir, un efecto moderado. 

*d. Estrategias de cuidado*

Para identificar la relación entre clase social y tipos de estrategias de cuidado se realiza un análisis, en primer lugar, del comportamiento de las estrategias de cuidado, compuestas por los criterios de género y remuneración. En segundo lugar, se analiza el comportamiento de esta misma variable en función de la clase social de los distintos establecimientos. Entonces, es posible dar cuenta de la frecuencia relativa porcentual de las estrategias de cuidado por cada tarea de cuidado consideradas como variables distintas con la información de la Tabla 3.
 
 AQUI VA LA TABLA 3 FRECUENCIA RELATIVA PORCENTUAL DE ESTRATEGIAS DE CUIDADO POR TAREAS
 
A partir de los datos, se puede reconocer que son las mujeres quienes se hacen mayormente cargo de todas las tareas de cuidado, ya sea remunerado o no. Por tanto, el cuidado es un trabajo realizado principalmente por mujeres. Aun así, se puede observar que ninguna de las tareas -a excepción de encargarse mayoritariamente del cuidado como fue representado en el Gráfico 1- es realizada exclusivamente por mujeres, de todas formas, la participación masculina es mínima.
 
Además, se identifica que para las tareas que sí son remuneradas, la distribución será también en todos los casos entre hombres y mujeres, pero nuevamente con una participación mayoritaria de mujeres, aunque con proporciones más cercanas. Por ejemplo, la preparación de la comida desde mujeres remuneradas consiste en el 22,22% del total de personas que realiza estas tareas, en contraste con un 2,22% de hombres remunerados que realizan esta actividad. En cambio, son un 73,33% de mujeres no remuneradas que se dedican a esta actividad mientras que los hombres no remunerados representan un 2,22% del total de personas que preparan la comida para las y los niños. Así, los hombres representan una mayor proporción dentro de las personas que realizan estos trabajos con remuneración que dentro de aquellas que los realizan sin remuneración.
 
Finalmente, es posible identificar que la estrategia de "Mujer remunerada" obtiene valores entre el 8,89% y 22,22% dentro de las distintas tareas que sí son remuneradas; los de "Mujer no remunerada" varían entre 73,33% y 95,56%; los de "Hombre remunerado" entre 2,22% y 8,89%; y los de "Hombre no remunerado" entre 2,22% y 17,78% de las personas que se hacen cargo de una tarea específica de cuidado.
 
 
AQUI VA LA TABLA 8 FRECUENCIA ABSOLUTA DE ESTRATEGIAS DE CUIDADO PARA ENCARGADE PRINCIPAL DEL CUIDADO SEGUN EL NIVEL SOCIOECONOMICO DE 

 


A partir de la Tabla 8, se puede identificar la relación entre clase social y estrategia de cuidado para la persona encargada principalmente de cuidado. En primer lugar se observa, al igual que en los análisis generales de la muestra, que no hay hombres que cumplan con el rol de hacerse cargo principalmente del cuidado, lo que implica que las estrategias "Hombre con remuneración" y "Hombre sin remuneración" no estén presentes en la tabla. Es decir, un elemento común a las distintas clases sociales, es que son mujeres las que se hacen cargo mayoritariamente del cuidado, por lo que se puede inferir que, independiente la clase social, los hombres no se hacen cargo del cuidado.
 
La tabla de contingencia muestra que las mujeres que realizan trabajos de cuidado en la clase baja en su totalidad no reciben remuneración por su labor. En cuanto a la clase media, solo una mujer recibe remuneración. Esto cambia en la clase alta donde 8 mujeres reciben remuneración mientras 7 no lo hacen. A nivel general de 45 mujeres que se encargan del cuidado en los hogares de la muestra, 36 realizan tareas de cuidado sin remuneración. Por lo que se puede observar que a nivel muestral las mujeres además de ser quienes principalmente realizan los trabajos de cuidado, lo hacen de manera gratuita (considerando también la Tabla 2), aunque a nivel socioeconómico alto la mayoría de las mujeres encargadas del cuidado reciben remuneración por ello.
 
AQUI VA LA TABLA 9 PRUEBA CHICUADRADO Y TAMAÑO DEL EFECTO CON V DE CRAMER PARA ESTRATEGIA DE CUIDADO


Si se considera la información anterior desde una muestra probabilísticamente construida, sería posible generar inferencias poblacionales a partir de esta. 

A continuación, se realiza el ejercicio analítico de inferencia estadística para comprobar el significado estadístico que pueden tener estas diferencias considerándolas desde el supuesto de un muestreo aleatorio. Se realiza la prueba de hipótesis Chi-cuadrado de Pearsons, al estar frente a dos variables categóricas con un nivel de confianza del 95%. Se identifica, con esta, que la relación entre los grupos es estadísticamente significativa, es decir, la variable estrategias de cuidado no es independiente de la clase social, sino que están relacionadas. Así, se rechaza la hipótesis nula de independencia de variables, arrojando que las diferencias que se reconocen en la tabla de contingencia pueden darse, con un 95% de confianza, en la población, esto es, mayor cantidad de mujeres remuneradas en la clase alta que en la clase media y media-baja y la ausencia de hombres encargados mayoritariamente del cuidado. Según el test V de Cramer, el tamaño del efecto de esta relación es de 0,593, es decir, un efecto moderado. 

Se observa que tanto la tabla de contingencia de frecuencias absolutas como la prueba de hipótesis Chi-cuadrado y de tamaño del efecto V de Cramer presentan los mismos resultados para la variable "Remuneración" y "Estrategia de cuidado" según clase social, dado que la estrategia de cuidado, en las distintas dimensiones del cuidado, se compone por remuneración y género y este último componente se mantiene constante en las estrategias observadas, ya que se presentan solo cuidadoras principales de género femenino, por lo que lo único que variaría dentro de las estrategias sería la remuneración. Por tal razón, las variaciones dentro de la variable "Remuneración" son las mismas que las que se presentan dentro de la variable "Estrategias de cuidado".


 
 

*5. Conclusiones*

De acuerdo a los resultados obtenidos, se puede aceptar la primera hipótesis, en la cual se concluye que en todos los casos quienes asumen el rol de encargada principal del cuidado son mujeres. No obstante, la coincidencia entre quien se hace cargo de la planificación del cuidado y del trabajo del cuidado es más recurrente en clases socioeconómicas más bajas. A esto se debe agregar que se aprueba el supuesto de que si el hombre se hace cargo de la planificación del cuidado, quien se hace cargo de las tareas es una mujer, ya que existen más hombres dedicados a las tareas de planificación que aquellos dedicados a las tareas de cuidado propiamente tales, generando proporciones diferenciadas dentro de estas actividades en relación con las mujeres. En segundo lugar, se constató que la  participación de las mujeres es mayoritaria en cuanto a las labores del cuidado y la planificación de este, además de que una gran proporción de la muestra, similar a aquella que lo considera como trabajo, no lo considera como un trabajo. Si bien, como se mencionó anteriormente, el rol de madre influye en la caracterización que se le da al trabajo de cuidado y las estrategias sobre este, no es determinante, ya que, como se encontró en los resultados, las mujeres de clase alta tienden a derivar el cuidado a terceros, esto puede deberse, principalmente, a sus condiciones económicas, educativas y laborales, según la bibliografía revisada y los resultados obtenidos. Pero, aunque hay nociones de considerar al cuidado como trabajo, la tendencia se mantiene radicalmente en que las mujeres asuman este trabajo. Por lo que se puede concluir, primeramente que, a pesar de que hay una evolución en la concepción de familia tradicional, los roles de género (rol de madre) continúan estando presente en la mentalidad de las mujeres al momento de decidir sobre qué estrategias de cuidado tomarán y adoptarán para sus vidas. 

En cuanto a la tercera hipótesis, esta no sería aceptada totalmente. Por un lado, se reconoce, tal como se planteó hipotéticamente, la presencia del trabajo de cuidado remunerado relacionado con la frecuencia de este en la clase alta. Pero, si bien los resultados para el colegio de estrato socioeconómico medio bajo y alto son los esperados, los resultados obtenidos en el colegio medio fueron mucho menos heterogéneos de lo que se pensaba. Estos se asemejan a los resultados de estrato medio bajo, es decir, existe casi nula presencia de trabajo remunerado y homogeneidad de trabajo no remunerado, distando de los resultados obtenidos del colegio de clase alta. 

Respecto a última hipótesis, se acepta la distinción de clases para las estrategias de cuidado, reconociéndose homogeneidad dentro de la dimensión de género de las estrategias y heterogeneidad dentro de la dimensión de remuneración de esta. Así, a diferencia de lo planteado hipotéticamente, la totalidad de personas encargadas del cuidado serán mujeres, sin ninguna excepción de género masculino. Pero algunas de ellas serán remuneradas y otras no. Esta variación en cuanto a la remuneración, difiriendo, en parte, de lo esperado, sólo se da entre la clase alta y media-baja, en conjunto con la clase media. Esta última no se comporta de manera "intermedia" entre las otras dos clases, en este sentido. Las mujeres son las que principalmente deciden sobre el cuidado independiente la clase social. Estas diferencias de estrategias según clase social son estadísticamente significativas, es decir, se podrían encontrar a nivel poblacional si el muestreo fuese probabilístico.

En síntesis, los resultados de nuestro objetivo general y la respuesta a nuestra pregunta de investigación corresponden a que las estrategias de cuidado efectivamente varían según las características socioeconómicas de los colegios, en cuanto a si se opta por el trabajo de cuidado remunerado. Estas diferencias son mínimas entre el colegio medio bajo y el medio, ya que en ambos las apoderadas optan principal o totalmente por estrategias de cuidado no remuneradas. Estas diferencias se exacerban en el colegio de nivel socioeconómico alto, donde la mayoría opta por estrategias remuneradas de cuidado. Por otra, parte quienes se hacen cargo de los trabajos de cuidado y la planificación de este son principalmente mujeres, independiente de la clase social, pudiendo así aprobar parcialmente la hipótesis referida al objetivo general.

A partir de los resultados obtenidos, se da cuenta claramente de la permanencia de roles de género al interior de la estructura familiar que actúan en perjuicio del género femenino, donde a pesar del creciente ingreso de las mujeres al mercado laboral, las labores relativas al cuidado siguen estando consagradas a este género. Además de ello es importante considerar que la situación para las cuidadoras de clases sociales más bajas resulta aún más complicada si se considera que el trabajo del cuidado suele no recibir remuneración alguna, asimismo para las cuidadoras de estratos socioeconómicos medios, que viven una situación similar. A partir de estas situaciones, se vuelve necesaria la implementación de políticas públicas que apunten a considerar esta labor como un trabajo que debe ser remunerado y asimismo dotarlo de una nueva valoración social, para ello es de vital importancia el garantizar condiciones de protección laboral para las y los cuidadores, como establecer horarios más flexibles para quienes estudian o trabajan y deben a la vez realizar trabajos de cuidado.

Además de ello, se vuelve necesario superar los roles tradicionales de género a modo de distribuir el trabajo del cuidado en ambos géneros, para ello es importante generar políticas públicas que apunten a una educación diferente en la que no se fomente la asignación de ciertos trabajos para ciertos géneros, para ello es necesaria la implementación de una  educación no sexista que cuestione los roles de género y no fomente la división sexual del trabajo.

Finalmente, en cuanto a las futuras líneas de análisis, sería provechoso realizar una investigación de tipo cualitativa. Llevar una investigación con este corte nos permitiría abordar la subjetividad de las mujeres y ahondar en temas como el rol de madre y la culpa que este genera al momento de decidir dejar a el hijo/a, e ir a trabajar. Además, permitiría ahondar en el significado que socialmente se da a cada un de las tareas que constituyen el trabajo de cuidado y cómo este peso influye en la vida de las mujeres.                

Como otra línea de análisis sería positivo ahondar sobre las condiciones laborales (entendiendo el cuidado como un trabajo, sea este remunerado o no), y cómo estas afectan, tanto a nivel tanto físico como psicológico, a quienes se hacen cargo. Estas son algunas de las líneas de investigación posibles y pertinentes a abordar, puesto que, al ser un tema contingente, hay diversas aristas posibles para seguir averiguando y aportando a un desarrollo feminista de la división de trabajos relacionados con cuidado.



















*6. Bibliografía*

Agencia de Calidad de la Educación. (2017). Resultados Educativos 2017. En https://www.agenciaeducacion.cl/

Arellano, O., Gómez, V., & Valenzuela, C. (2017). Negociaciones en familia: género, trabajo y cuidado en Chile. Revista Estudos Feministas, 25(2), 661-682. https://dx.doi.org/10.1590/1806-9584.2017v25n2p661

Armijo, L. (2016). Ciudadanía y cuidado en España: El dilema trabajo/familia según las madres trabajadoras. Psicoperspectivas, 15 (3), 87-100. DOI: 10.5027/PSICOPERSPECTIVAS-VOL15- ISSUE3-FULLTEXT-789 Recibido: 16-10-2015 Aceptado: 08-11-2016

Arenas, N.. (2006). El cuidado como manifestación de la condición humana. Revista de la Facultad de Ciencias de la Salud, 10, pp. 12-17.

Batthyány, K. (2007) Articulación entre vida laboral y vida familiar. Las prácticas de cuidado infantil de trabajadoras asalariadas de Montevideo. Consejo Latinoamericano de Ciencias Sociales (CLACSO). Buenos Aires.

Bourdieu, P. (2000). La dominación masculina. Barcelona, Argentina: Anagrama.

Cano, T. (2018). Los cuidados en la práctica. Clase social y estrategias familiares en el cuidado a mayores con dependencias severas. Revista Internacional de Sociología, 76(3), 103.

Caro, P., Saracostti, M., Kinkead, A., & Grau, M. O. (2017). Niñez y adultez. Diálogos frente a tensiones familiares, laborales y del cuidado. RLCSNJ.

Esquivel, V. (2011). La economía del cuidado en América Latina. Panamá: PNUD.

Faur, E., Esquivel, V., & Jelin, E. (2012). Las lógicas del cuidado infantil: Entre las familias, el Estado y el mercado.

Fernández Lao, Isabel, Silvano Arranz, Agustina, & Pino Berenguer, Margarita Del. (2013). Percepción del cuidado por parte del cuidador familiar. Index de Enfermería, 22(1-2), 12-15. 

Flaquer, L., Pfau-Effinger, B., & Leiras, A. A. (2014). El trabajo familiar de cuidado en el marco del estado de bienestar. Cuadernos de relaciones laborales, 32(1), 11.

García-Calvente, M. D. M., Mateo-Rodríguez, I., & Eguiguren, A. P. (2004). El sistema
informal de cuidados en clave de desigualdad. Gaceta Sanitaria, 18(4), 132-139.

Garrido, L. A. (2016). Ciudadanía y cuidado en España: El dilema trabajo/familia según las madres trabajadoras/Citizenship and care in Spain: Work/Family dilemma by working mothers. Psicoperspectivas, 15(3), 87.

Instituto Nacional de Estadísticas (2017) CENSO. Santiago, Chile. 

Kirkwood, J., & Aguirre, S. M. (1987). Feminarios. Ediciones Documentas.

Laia Castelló Santamaría . (2011). Trabajo de cuidado, género y clase social. Remedios desiguales a un problema común. Sociología del trabajo 73, Otoño 2011 , 154.

Larrañaga, I., Martín, U., Bacigalupe, A., Begiristáin, J. M., Valderrama, M. J., & Arregi, B. (2008). Impacto del cuidado informal en la salud y la calidad de vida de las personas cuidadoras: análisis de las desigualdades de género. Gaceta sanitaria, 22(5), 443-450.

Masanet, E., & La Parra, D. (2011). Relación entre el número de horas de cuidado informal y el estado de salud mental de las personas cuidadoras. Revista Española de Salud Pública, 85(3), 257-266.

Ministerio del Desarrollo Social (2015). Encuesta de caracterización Socioeconómica Nacional. Santiago. 

Moreno-Roldán, M. R., Agudelo-Bedoya, M. E., & Alzate-Pulgarín, V. (2018). Voces a escuchar en el cuidado: ¿qué dicen los niños y las niñas?. Revista Latinoamericana de Ciencias Sociales, Niñez y Juventud, 16(1), 227-237.

Ruiz, I. J., & Nicolás, M. M. (2018). La cuidadora familiar: sentimiento de obligación naturalizado de la mujer a la hora de cuidar. Enfermería Global, 17(49), 420-447.

Torns, T. (2008). El trabajo y el cuidado: cuestiones teórico-metodológicas desde la perspectiva de género. Empiria: Revista de metodología de ciencias sociales, (15), 53-73.

UNESCO. (25 de Diciembre de 2018). La Atención y Educación de la Primera Infancia. Obtenido de UNESCO:Organización de las Naciones Unidas para la Educacion, la Ciencia y la Cultura:  https://es.unesco.org/themes/atencion-educacion-primera-infancia.com 

Urrutia, V. G., Faúndez, O. A., & Contreras, C. V. (2017). Negociaciones en familia: género, trabajo y cuidado en Chile. Estudos Feministas, 25(2), 661-682.

Vaquiro Rodríguez, S., & Stiepovich Bertoni, J. (2010). Cuidado informal, un reto
asumido por la mujer. Ciencia y enfermería, 16(2), 17-24.

Vera Rojas, W., Montes Maldonado, C., & De la Barra Urquieta, C. (2016). Los cuidados en infancia: Regímenes y arreglos familiares en Chile y Uruguay. Psicoperspectivas, 15(3), 34-45

Weber, M., (2008) "División de poder en la comunidad: clases, estamentos y partidos", en Economía y sociedad, Fondo de Cultura Económica, México, pp. 682-694. 



*7. Anexos*

*Operacionalización:*

AQUI VA LA TABLA DE : "Constructo
Dimensiones
Indicadores nominales
Nivel de medición
Indicadores operacionales
Estrategias de cuidado:"


*Nota:*

El constructo principal de la investigación corresponde a la variable dependiente de la hipótesis principal, el cual es "Estrategias de Cuidado", entendidas como las formas de hacerse cargo del cuidado, se dividirán en tres dimensiones: (i) características de quien decide sobre el cuidado, que refiere a las características de la persona que se hace cargo de las planificaciones/decisiones del cuidado del niño/a/e; (ii) características del cuidador/a principal, y que se orienta a describir el perfil del cuidador en tanto cuidador. Se entiende por cuidador como la persona que se hace cargo mayormente del niño/a desde la gestación hasta los 8 años (UNESCO, 2018); (iii) distribución según género de las tareas de cuidado, orientado a saber cuál es la asignación de las tareas de cuidado del niño/a en relación con el género. Para efectos del análisis, se entenderá que las estrategias de cuidado están compuestas por el género y la remuneración de la persona (dentro de las distintas dimensiones en las que se puede evaluar una estrategia de cuidado). Así, existirán cuatro tipos de estrategias de cuidado: 1. Mujer con remuneración, 2. Mujer sin remuneración, 3. Hombre con remuneración, 4. Hombre sin remuneración.
Por otro lado, se entenderá clase social como posición de las personas dentro del espacio social según su lugar en el sistema económico (Weber, 2018). Operativamente, en el presente trabajo estará dada por el nivel de ingresos y de escolaridad de las y los apoderados del establecimiento educacional y el porcentaje de niñas y niños en condición de vulnerabilidad. Siendo "alto" un establecimiento en que "La mayoría de los apoderados ha declarado tener 16 o más años de escolaridad y un ingreso del hogar de $1.460.001 o más." y "9% o menos de los estudiantes se encuentra en condición de vulnerabilidad social."; "medio" uno en que "La mayoría de los apoderados ha declarado tener entre 12 y 13 años de escolaridad y un ingreso del hogar que varía entre $490.001 y $740.000." y "Entre 36,01% y 54% de los estudiantes se encuentra en condición de vulnerabilidad social." ; y "bajo" un establecimiento que "La mayoría de los apoderados ha declarado tener entre 10 y 11 años de escolaridad y un ingreso del hogar que varía entre $290.001 y $460.000." y "Entre 57,01% y 75% de los estudiantes se encuentra en condición de vulnerabilidad social." (Agencia de Calidad de la Educación, 2017)








*Plan de análisis*

Con los datos recogidos se otorgará números a las respuestas del cuestionario para sistematizarlas. Luego, se trabajará con los datos sistematizados en el programa R-Studio. En todas las recodificaciones se limpiará los NA, es decir, no serán considerados en el análisis.

1. Se pasarán las respuestas "Masculino" a 1 "Femenino" a 2 y "Otro" a 3,  en referencia a la pregunta 12. 

2. Se pasará las respuestas de remuneración a números para la sistematización de estas. La respuestas que indican que se recibe remuneración pasarán a ser 1 y las que indican que  no se recibe remuneración (No) pasarán a ser 2, referentes a las pregunta 10. 

3. Se recodificará las respuestas de la pregunta 10 y 12 de manera combinada, para generar la variable "Estrategia de Cuidado" con los códigos 1: Mujer con remuneración, 2: Mujer sin remuneración, 3: Hombre con remuneración, 4: Hombre sin remuneración. 

4. Los análisis univariados descriptivos a realizar serán las descripciones de todos los grupos, es decir, caracterizar cómo son las variables para el "Colegio Carlos Pezoa Véliz", "Colegio Excelsior" y "Saint George College", en conjunto. Esto se realizará a partir del análisis de las variables "Género", "Remuneración" y "Estrategias de Cuidado" (la cual incluye a las anteriores) dentro del cuidado en general, la decisión respecto al cuidado y distintas tareas de cuidado. Para esto realizarán una serie de tablas de frecuencias donde se expondrán y se describirán los resultados de la recolección de datos. 

5. Se codificarán las respuestas de la variable "Relación con niño", de manera que "Madre" y "Abuela" queden codificadas como 1 y el resto de las respuestas como 2.

6. En otra tabla de frecuencias se expondrán los datos de la pregunta 13 del cuestionario, la cual está enfocada en dilucidar si las apoderadas entrevistados consideran las tareas cotidianas que conlleva cuidar a un niño como trabajo.

7. Para responder a la hipótesis 1, se procederá a analizar los datos codificados y sistematizados de la variable "Género". Se analizará esta variable de manera univariada para la muestra en general y bivariada con una tabla de contingencia según nivel socioeconómico del colegio ("Tipo de colegio"). Finalmente se realizarán inferencias poblacionales bivariadas, a pesar de no contar con una muestra probabilísticamente construida, sobre la relación entre estas variables. Para ello se realizará la prueba de hipótesis para comprobar si se acepta o rechaza la hipótesis nula de independencia de variables entre estas dos variables señaladas. Entonces, la  hipótesis nula será (H0): no hay una relación entre las variables "Tipo de colegio" y "Género"; y la hipótesis alternativa será (HA): existe una relación entre las variables "Tipo de colegio" y "Género". Esta prueba será realizada a través del Test ji-cuadrado de Pearson (X2), ya que se presentan dos variables categóricas, con un nivel del 95% de confianza, con la cual se podrá rechazar o no rechazar la hipótesis nula de independencia de variables. Esto se realizará al comparar el X2 teórico o crítico, o bien, el p valor asociado a este, con el X2calculado, o bien, el p valor calculado, a través de el programa R-Studio. Con esta comparación será posible reconocer si se rechaza la hipótesis de independencia de variables a nivel poblacional.

8. Se aplicará el Test V de Cramer para reconocer el tamaño del efecto de la relación previamente identificada, es decir, responder a la pregunta:¿Qué tan fuerte es la relación entre el Tipo de colegio  y Género nivel poblacional?

9. Para responder a la hipótesis 2 se realizará un análisis descriptivo univariado, en primer lugar, de la variable "Relación con niño" creada a partir de la pregunta xx y codificada de la manera señalada en el punto 6. En segundo lugar, se analizará la variable "Consideración como trabajo" reada a partir de la pregunta xx y codificada de la manera señalada en el punto. Con ambas variables se realizará un análisis que pueda dar cuenta de los resultados pertinentes para la hipótesis 2.

10. Para responder a la hipótesis 3 se comenzará por realizar un análisis descriptivo univariado de la variable "Remuneración" para después analizar de manera conjunta a esta variable según "Tipo de colegio" (clase social) a partir de una tabla de contingencia. Luego de esto, se realizarán inferencias poblacionales bivariadas, a pesar de no contar con una muestra probabilísticamente construida, sobre la relación entre estas variables. Para ello se realizará la prueba de hipótesis para comprobar si se acepta o rechaza la hipótesis nula de independencia de variables entre estas dos variables señaladas. Entonces, la  hipótesis nula será (H0): no hay una relación entre las variables "Tipo de colegio" y "Remuneración"; y la hipótesis alternativa será (HA): existe una relación entre las variables "Tipo de colegio" y "Remuneración". Esta prueba será realizada a través del Test ji-cuadrado de Pearson (X2), ya que se presentan dos variables categóricas, con un nivel del 95% de confianza, con la cual se podrá rechazar o no rechazar la hipótesis nula de independencia de variables. Esto se realizará al comparar el X2 teórico o crítico, o bien, el p valor asociado a este, con el X2calculado, o bien, el p valor calculado, a través de el programa R-Studio. Con esta comparación será posible reconocer si se rechaza la hipótesis de independencia de variables a nivel poblacional.

11. Se aplicará el Test V de Cramer para reconocer el tamaño del efecto de la relación previamente identificada, es decir, responder a la pregunta:¿Qué tan fuerte es la relación entre el Tipo de colegio y Remuneración a nivel poblacional?

12. Para responder a la hipótesis 4, en primer lugar, se realizará un análisis descriptivo univariado de la variable "Estrategia de cuidado" y, luego, se analizará la tabla de contingencia que presenta a esta misma variable según "Tipo de colegio" (clase social). A partir de esta misma tabla de contingencia se realizarán inferencias poblacionales bivariadas, a pesar de no contar con una muestra probabilísticamente construida, sobre la relación entre estas variables. Para ello se realizará la prueba de hipótesis para comprobar si se acepta o rechaza la hipótesis nula de independencia de variables entre estas dos variables señaladas. Entonces, la  hipótesis nula será (H0): no hay una relación entre las variables "Tipo de colegio" y "Estrategias de Cuidado"; y la hipótesis alternativa será (HA): existe una relación entre las variables "Tipo de colegio" y "Estrategias de Cuidado". Esta prueba será realizada a través del Test ji-cuadrado de Pearson (X2), ya que se presentan dos variables categóricas, con un nivel del 95% de confianza, con la cual se podrá rechazar o no rechazar la hipótesis nula de independencia de variables. Esto se realizará al comparar el X2 teórico o crítico, o bien, el p valor asociado a este, con el X2calculado, o bien, el p valor calculado, a través de el programa R-Studio. Con esta comparación será posible reconocer si se rechaza la hipótesis de independencia de variables a nivel poblacional.

13. Finalmente, se aplicará el Test V de Cramer para reconocer el tamaño del efecto de la relación previamente identificada, es decir, responder a la pregunta:¿Qué tan fuerte es la relación entre el Tipo de colegio y Estrategia de Cuidado a nivel poblacional?










{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
